# Generated by Django 3.1.7 on 2021-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(blank=True, null=True)),
                ('back', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
